# Домашняя работа 
Создать 2 массива NumPy
Один из случайных чисел, второй - использую arange Или linspace
После этого выполнить математические операции- сложить, перемножить, делить
Найти максимальный элемент в каждой строчке и столбце первого массива (из случайных чисел_
Найти максимальный элемент в из 2 массивов
Изменить форму массива

In [1]:
import numpy as np

In [2]:
ar1 = np.random.randint(1, 10,  size = (3,3))
ar1

array([[4, 7, 5],
       [5, 8, 3],
       [6, 8, 8]])

In [3]:
ar2 = np.linspace(1, 20, 9, dtype = int)
ar2

array([ 1,  3,  5,  8, 10, 12, 15, 17, 20])

In [4]:
ar2 = ar2.reshape(3,3)
ar2


array([[ 1,  3,  5],
       [ 8, 10, 12],
       [15, 17, 20]])

In [5]:
ar_sum = ar2 + ar1
ar_mult = ar2 * ar1
ar_div = ar2 / ar1
ar_sum, ar_mult, ar_div

(array([[ 5, 10, 10],
        [13, 18, 15],
        [21, 25, 28]]),
 array([[  4,  21,  25],
        [ 40,  80,  36],
        [ 90, 136, 160]]),
 array([[0.25      , 0.42857143, 1.        ],
        [1.6       , 1.25      , 4.        ],
        [2.5       , 2.125     , 2.5       ]]))

In [6]:
(ar1.min(), ar1.max()), (ar2.min(), ar2.max())


((3, 8), (1, 20))

In [7]:
ar1.max(axis = 1)

array([7, 8, 8])

In [8]:
ar1.max(axis = 0)

array([6, 8, 8])

In [9]:
max(ar1.max(),ar2.max())

20